Documentation fixes
cloudfoundry/uaa pull request #2150
Opened 2022-12-29 19:50 UTC by strehle

After jwtClientAuthentication clarify to omit relyingPartySecret

2023-01-05 01:24 UTC, swalchemist reviewed
Why are the changes only in a test file? Is this fixing a broken test?

2023-01-05 11:40 UTC, strehle commented
> Why are the changes only in a test file? Is this fixing a broken test?

these texts will be used to create https://docs.cloudfoundry.org/api/uaa so this is the change after private_key_jwt is possible for Azure and then I would like to deprecate the use of secrets for OIDC IdPs

2023-01-09 20:28 UTC, swalchemist requested changes

2023-01-09 20:28 UTC, swalchemist commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
> +                fieldWithPath("config.clientAuthInBody").optional(false).type(BOOLEAN).description("Only effective, if relyingPartySecret is defined. Sends the client credentials in the token retriev
Typo - change "reommended" to "recommended".

2023-01-09 20:28 UTC, swalchemist commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
> +    private FieldDescriptor relyingPartySecret = fieldWithPath("config.relyingPartySecret").constrained("Not recommended, but required if the external IdP does not support private_key_jwt.").type(STR
Typo - change "reommended" to "recommended".

2023-01-09 20:28 UTC, swalchemist commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
> +                fieldWithPath("config.jwtClientAuthentication").optional(null).type(OBJECT).description("<small><mark>UAA 76.5.0</mark></small> Only effective, if relyingPartySecret is not set or nul
This part would be more understandable without the comma: "Only effective if relyingPartySecret is not set or null."

2023-01-10 00:30 UTC, swalchemist requested changes

2023-01-10 00:30 UTC, swalchemist commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
> +    private FieldDescriptor relyingPartySecret = fieldWithPath("config.relyingPartySecret").constrained("Not recommended, but required if the external IdP does not support private_key_jwt.").type(STR
The "as replacement" part is a bit confusing. Maybe it means "It is recommended to set `jwtClientAuthentication:true` instead of setting relyingPartySecret."?

But the first sentence says that if the IDP doesn't support private_key_jwt, we must set relyingPartySecret, so that can't be quite right.

2023-01-10 00:30 UTC, swalchemist commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
> +                fieldWithPath("config.clientAuthInBody").optional(false).type(BOOLEAN).description("Only effective, if relyingPartySecret is defined. Sends the client credentials in the token retriev
As above, for proper grammar, remove the comma so it says "Only effective if relyingPartySecret is defined."

Also as above, the "as replacement" part is a bit confusing.

2023-01-10 00:30 UTC, swalchemist commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/providers/IdentityProviderEndpointDocs.java
> +                fieldWithPath("config.jwtClientAuthentication").optional(null).type(OBJECT).description("<small><mark>UAA 76.5.0</mark></small> Only effective, if relyingPartySecret is not set or nul
Needs an article - "...according to _the_ OIDC or OAuth2 (RFC 7523) standard..."

2023-01-10 10:04 UTC, strehle commented
@swalchemist thanks for the review. please have a look on the change now

2023-01-19 01:21 UTC, swalchemist approved these changes
Still has the confusing comma in "Only effective, if relyingPartySecret is defined."

But no big deal.

2023-01-19 18:31 UTC, swalchemist approved these changes

2023-01-31 23:50 UTC, swalchemist approved these changes

2023-02-07 06:32 UTC, merged