feat: Increase the client redirect_uri length limit
cloudfoundry/uaa pull request #2245
Opened 2023-03-16 19:25 UTC by hsinn0

- Change the databaes data type from varchar to text type as mysql varchar type is subject to the table's column size limit

[#183903458]

2023-03-16 20:51 UTC, peterhaochen47 approved these changes

2023-03-17 15:39 UTC, strehle requested changes
please revert import changes

2023-03-17 15:39 UTC, strehle commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ClientAdminEndpointsIntegrationTests.java
> -import java.util.ArrayList;
Can you please revert import changes.
There is an ongoning discussion about clean code but we have different view on that but therefore please exclude such changes where they are not needed

2023-03-17 15:39 UTC, strehle commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointsMockMvcTests.java
> -import java.util.ArrayList;
See other comments about import changes

2023-03-17 16:16 UTC, hsinn0 commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ClientAdminEndpointsIntegrationTests.java
> -import java.util.ArrayList;
Done

2023-03-17 16:16 UTC, hsinn0 commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/clients/ClientAdminEndpointsMockMvcTests.java
> -import java.util.ArrayList;
Done

2023-03-17 18:58 UTC, merged

2023-03-17 18:59 UTC, peterhaochen47 commented
Merged as all comments have been addressed.