Fix: Fixing performance while calling containsAll over list
cloudfoundry/uaa pull request #2272
Opened 2023-04-05 17:34 UTC by saurabh-rahate

2023-04-12 16:32 UTC, strehle approved these changes
ok for me

2023-04-12 16:33 UTC, strehle commented
@Tallicia  @bruce-ricard  any concerns

2023-04-12 19:46 UTC, Tallicia commented
The 8 test look good and the optimization does as well.

2023-04-12 19:46 UTC, Tallicia approved these changes
Nice improvement.

2023-04-12 19:48 UTC, Tallicia commented
Would be nice to see performance tests to see if sets are of large enough size in practice to know the real world performance improvement.

2023-04-12 20:05 UTC, bruce-ricard requested changes
Thank you for making performance improvements. 

To be perfectly frank, I am not convinced that this change will improve performance in the general practical world. I don't know if most objects don't have one or two roles. And this change forces the creation of 2 new hashsets every single time.

Also, we cannot find any usage of that `equals` method in the UAA code base. I don't think that this change will have any impact at all. 

Additionally, I am not convinced that Java doesn't already use HashSets internally to resolve `containsAll` calls on `List` object.

@Tallicia and me

2023-04-12 20:05 UTC, bruce-ricard commented on server/src/main/java/org/cloudfoundry/identity/uaa/user/UserInfo.java
> +        return new HashSet<>(l1).containsAll(l2) && new HashSet<>(l2).containsAll(l1);
It seems to me like we should be able to leverage the `Set` `equals` [method](https://docs.oracle.com/javase/7/docs/api/java/util/Set.html#equals(java.lang.Object))

The linked documentation states:

>Returns true if the specified object is also a set, the two sets have the same size, and every member of the specified set is contained in this set

We should be able to write
```
return new HashSet<>(l1).equals(new HashSet<>(l2))
```

2023-04-13 19:50 UTC, saurabh-rahate commented on server/src/main/java/org/cloudfoundry/identity/uaa/user/UserInfo.java
> +        return new HashSet<>(l1).containsAll(l2) && new HashSet<>(l2).containsAll(l1);
Changed implementation to use `Set` `equals` method.

2023-04-20 09:50 UTC, strehle commented
I have tested this and created an extra PR https://github.com/cloudfoundry/uaa/pull/2294
With a test of role about 10000 the difference is 300 ms compared to 30 ms , in case of more e.g. 100000xxx it sometimes runs into many seconds, so that I decided to stay only with 10000
So it brings the expected result from times described here:
https://www.baeldung.com/java-hashset-arraylist-contains-performance
List -> O(mn)
HashSet -> O(n)

Finally, I will merge this, so thanks for your PR

2023-04-20 09:59 UTC, merged