fix client admin rest call with empty secret - alternative PR
cloudfoundry/uaa pull request #2572
Opened 2023-10-24 15:42 UTC by strehle

This PR simply uses PasswordValidatorUtil but set the password minLength to 1 which was the default because it was in code The minLength for clients should be 0 and this was the case before

Same Tests as before, means, with Default Policy the empty secret is allowed, with the strictPolicy not, see testEmptyClientSecret

2023-10-24 16:39 UTC, strehle commented on uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml
> +        <constructor-arg name="minLength" value="${password.policy.global.minLength:1}"/>
Documentation says 0 is allowed , really ?

2023-10-24 16:41 UTC, strehle commented
After thinking about I see that minLength for passwords and secrets is 0 by default so then I would go with it, if you have no concerns and completly rely on the PasswordValidor rules, means I will update again to minLength:0

2023-10-24 17:00 UTC, bruce-ricard requested changes
Thanks Markus. This is IMO a lot better. I just have a couple small comments.

2023-10-24 17:00 UTC, bruce-ricard commented on server/src/main/java/org/cloudfoundry/identity/uaa/util/PasswordValidatorUtil.java
> +        int minLength = Math.max(0, policy.getMinLength());
Is there a reason you didn't just delete the line?

`minLength` is now exactly `policy.getMinLength()`.

2023-10-24 17:00 UTC, bruce-ricard commented on server/src/test/java/org/cloudfoundry/identity/uaa/zone/ZoneAwareClientSecretPolicyValidatorTests.java
> +    void testEmptyClientSecretAllowed() {
Could we name this test:

```
testEmptyClientSecretAllowedForBackwardsCompatibility
```

Because we don't really _want_ this feature. We need to keep it for backwards compatibility. Correct?

2023-10-24 17:00 UTC, bruce-ricard commented on server/src/test/java/org/cloudfoundry/identity/uaa/zone/ZoneAwareClientSecretPolicyValidatorTests.java
> +    void testEmptyClientSecretForbidden() {
It's a bit odd to have 2 tests that have opposite descriptions.

Now we have a test that says "empty client secret is allowed" and one that says "empty client secret is forbidden".

Maybe `defaultPolicyAcceptsEmptySecret` and `strictPolicyRejectsEmptySecret` ?

2023-10-24 17:00 UTC, bruce-ricard commented on uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml
> +        <constructor-arg name="minLength" value="${password.policy.global.minLength:1}"/>
I still don't understand this change. I don't care too much about it, but requiring a password of minimum length 1 is odd.

We can leave it as is for now.

2023-10-24 17:44 UTC, bruce-ricard commented on uaa/src/main/webapp/WEB-INF/spring/scim-endpoints.xml
> +        <constructor-arg name="minLength" value="${password.policy.global.minLength:1}"/>
OK I see that you reverted that change. LGTM.

If someone wants to enforce more characters, they can do that by setting the policy.

2023-10-24 22:26 UTC, peterhaochen47 commented
This PR is indeed simpler than the first #2571, but it does change the current behavior of UAA (and the 4 failing tests, before [this commit](https://github.com/cloudfoundry/uaa/pull/2572/commits/b30c52f7e1e7f0e2802c9871ed3c50a8567fedc7) was made to remove/modify the existing tests, are evidence). The behavior in question (not allowing user password to be an empty string) seems contradictory to [our uaa-release doc](https://github.com/cloudfoundry/uaa-release/blob/b27bedbe7e5ff1768be28c29ffaab99731e1bc77/jobs/uaa/spec#L620), but its addition seems deliberate based on the [original tracker story](https://www.pivotaltracker.com/n/projects/997278/stories/136465473) associated with this restriction. Hence, I suspect that this change (removing the restriction) might introduce a new regression (possibly the one that the original tracker story tries to address).

2023-10-25 18:38 UTC, strehle commented
close this , now, was related to https://github.com/cloudfoundry/uaa/issues/2570 but no successful tests

2023-10-25 18:38 UTC, closed without merging